title: "Timmyâ€™s Dev Magazine"
description: "Technical insights, tutorials, UX thinking, front-end development, productivity, and modern web design trends."

url: "https://timmygospel.github.io"
baseurl: ""

github_username: timmygospel
twitter_username: timmygospel

minimal_mistakes_skin: default
search: true

markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

after_head: |
  <link rel="stylesheet" href="/assets/css/smashing.css">

author:
  name: "Timmy Gospel"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Developer, designer, and writer exploring the craft of the web."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/timmygospel"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/timmygospel"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tag/
